version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: staymates-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: staymates
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
