global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.1.10:9090']

  # StayMates application
  - job_name: 'staymates'
    static_configs:
      - targets: ['staymates:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Node.js application metrics
  - job_name: 'staymates-node'
    static_configs:
      - targets: ['staymates:3000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s 